import pandas as pd
import numpy as np

def calculate_technical_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes key technical indicators for stock data.
    Assumes df contains columns: 'Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Stock'
    """
    # Create a copy to avoid SettingWithCopyWarning
    df = df.copy()
    
    # Sort data by Stock and Date to ensure proper chronological order
    df = df.sort_values(by=["Stock", "Date"]).reset_index(drop=True)
    
    # 1. Moving Averages
    df["MA_10"] = df.groupby("Stock")["Close"].transform(lambda x: x.rolling(window=10).mean())
    df["MA_50"] = df.groupby("Stock")["Close"].transform(lambda x: x.rolling(window=50).mean())
    
    # 2. Daily Returns
    df["Daily_Return"] = df.groupby("Stock")["Close"].pct_change()
    
    # 3. Volatility (20-day standard deviation of daily returns)
    df["Volatility"] = df.groupby("Stock")["Daily_Return"].transform(lambda x: x.rolling(window=20).std())
    
    # 4. Price Ranges & Spreads
    df["Price_Range"] = df["High"] - df["Low"]
    df["Open_Close_Diff"] = df["Close"] - df["Open"]
    
    # 5. Relative Strength Index (RSI - 14 days)
    def calculate_rsi(series: pd.Series, period: int = 14) -> pd.Series:
        delta = series.diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
        
        # Avoid division by zero
        rs = gain / np.where(loss == 0, 1e-9, loss)
        rsi = 100 - (100 / (1 + rs))
        return rsi

    df["RSI_14"] = df.groupby("Stock")["Close"].transform(lambda x: calculate_rsi(x))
    
    # 6. MACD (Moving Average Convergence Divergence)
    # EMA 12 and EMA 26
    def calculate_macd(series: pd.Series) -> pd.DataFrame:
        ema_12 = series.ewm(span=12, adjust=False).mean()
        ema_26 = series.ewm(span=26, adjust=False).mean()
        macd_line = ema_12 - ema_26
        signal_line = macd_line.ewm(span=9, adjust=False).mean()
        macd_diff = macd_line - signal_line
        return pd.DataFrame({
            "MACD_Line": macd_line,
            "MACD_Signal": signal_line,
            "MACD_Diff": macd_diff
        })
        
    macd_data = df.groupby("Stock")["Close"].apply(lambda x: calculate_macd(x)).reset_index(level=0, drop=True)
    df = pd.concat([df, macd_data], axis=1)
    
    # Fill NaN values generated by rolling metrics with sensible defaults rather than dropping them.
    # Dropping them cuts off the first 50 days of any chart, and returns completely empty DataFrames
    # for short periods like 1D, 5D, and 1M since MA_50 is all NaN.
    df["MA_10"] = df["MA_10"].fillna(df["Close"])
    df["MA_50"] = df["MA_50"].fillna(df["Close"])
    df["Daily_Return"] = df["Daily_Return"].fillna(0.0)
    df["Volatility"] = df["Volatility"].fillna(0.0)
    df["RSI_14"] = df["RSI_14"].fillna(50.0) # Neutral RSI
    df["MACD_Line"] = df["MACD_Line"].fillna(0.0)
    df["MACD_Signal"] = df["MACD_Signal"].fillna(0.0)
    df["MACD_Diff"] = df["MACD_Diff"].fillna(0.0)
    
    return df

if __name__ == "__main__":
    print("Testing technical indicators generator...")
    # Mock data
    dates = pd.date_range(start="2026-01-01", periods=60)
    mock_data = pd.DataFrame({
        "Date": dates,
        "Open": np.random.uniform(100, 110, size=60),
        "High": np.random.uniform(110, 120, size=60),
        "Low": np.random.uniform(90, 100, size=60),
        "Close": np.random.uniform(95, 115, size=60),
        "Volume": np.random.randint(1000, 5000, size=60),
        "Stock": ["TEST.NS"] * 60
    })
    
    result = calculate_technical_indicators(mock_data)
    print("Columns calculated:", result.columns.tolist())
    print("Sample shape:", result.shape)
